### ISSUE TITLE
Feature Request: Support Jira Rate Limit

### ISSUE THREAD

**Issue by faltfe** [Qytera-Gmbh/cypress-xray-plugin#370]
Hi,
I really appreciate your work. The plugin works great but your company did some changes on the Jira server. The problem is now that we get many 429 Too many requests error responses due to the new limitation of 

> The REST API access will be allowed up to 1 requests per second (1 req/sec)

Our question is if there is somekind of support that we can limit the amount of requests?

- Jira Version: Jira v9.12.10
- Cypress Version: 13.13.2
- Cypress Xray Plugin Version: 7.1.0

---

Furthermore, I want to provide some information I found while resource:
- https://developer.atlassian.com/cloud/jira/platform/rate-limiting/
- General request optimization stategies suggested by our company
  - always make use of sessions
  - specify the only required fields in header
  - use small request chunks (e.g. 25 issue at once) instead of requesting everything in one try
  - evalute 'x-ratelimit-interval-seconds' and 'x-ratelimit-fillrate' header for a perfect request rate: x-ratelimit-interval-seconds / x-ratelimit-fillrate  is the optimal time in between two requests you should wait
  - evaluate 'retry-after' header in every response to avoid HTTP 429; it indicates how long you should wait in seconds for the next request if you breached rate limiting.
-  https://www.atlassian.com/blog/developer/handling-rate-limiting-in-javascript example with sourcecode

**Comment by csvtuda** [comment]
Hi @faltfe,

thanks for the issue!

> Our question is if there is somekind of support that we can limit the amount of requests?

Unfortunately not, currently. But seeing that #366 also encountered 429 Too Many Requests, I really need to add rate limiting configurability.

**Comment by csvtuda** [comment]
Hi @faltfe,

I have just released version [7.2.0](https://www.npmjs.com/package/cypress-xray-plugin/v/7.2.0) ([changelog](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/main/CHANGELOG.md#720)). It includes a new [rate limiting feature](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/faq/#rate-limiting), that simply works on a _max requests per second_ basis. It's not as sophisticated as the ones in your linked resources, because those will take more time to implement, and I did'nt want to keep everyone waiting too long. Maybe I'll implement the better approach in a future release.

Please let me know if the way rate limiting works for now solves your problem.

**Comment by faltfe** [comment]
Hi @csvtuda.
thanks for the fix. But it seems, that it did not resolve your problem.

I've updated to 7.2.0 and set the new setting `requestsPerSecond` to 0.95 and also to 0.25 but the error was the same. The upload is working when running a single test. But the upload is not working, when running your test suite. At the moment there are 356 tests linked within Jira to one test plan executed by the test execution.

Attached you can find some error logs:
[importFeatureError.json](https://github.com/user-attachments/files/16749529/importFeatureError.json)
[importExecutionCucumberMultipartError.json](https://github.com/user-attachments/files/16749564/importExecutionCucumberMultipartError.json)
[14_34_34_POST_https_devstack.vwgroup.com_jira_rest_api_latest_search_response.json](https://github.com/user-attachments/files/16749585/14_34_34_POST_https_devstack.vwgroup.com_jira_rest_api_latest_search_response.json)

> error	26-Aug-2024 15:38:08	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:08	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:08	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:08	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
build	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ INFO    │ Importing Cucumber execution...
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber execution: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importExecutionCucumberMultipartError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/importFeatureError.json
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber features: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Failed to search issues: Request failed with status code 429
error	26-Aug-2024 15:38:09	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/searchError.json
error	26-Aug-2024 15:38:10	│ Cypress Xray Plugin │ ERROR   │ Failed to search issues: Request failed with status code 429
error	26-Aug-2024 15:38:10	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/searchError.json
error	26-Aug-2024 15:38:10	│ Cypress Xray Plugin │ ERROR   │ Failed to search issues: Request failed with status code 429
error	26-Aug-2024 15:38:10	│ Cypress Xray Plugin │ ERROR   │ Complete error logs have been written to: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/logs/searchError.json
build	26-Aug-2024 15:38:18	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/raven/latest/import/feature?projectKey=TC to respond... (10 seconds)
build	26-Aug-2024 15:38:18	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/raven/latest/import/feature?projectKey=TC to respond... (10 seconds)
build	26-Aug-2024 15:38:18	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/raven/latest/import/feature?projectKey=TC to respond... (10 seconds)
build	26-Aug-2024 15:38:19	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/raven/latest/import/feature?projectKey=TC to respond... (10 seconds)
build	26-Aug-2024 15:38:19	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/raven/latest/import/feature?projectKey=TC to respond... (10 seconds)
build	26-Aug-2024 15:38:19	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/raven/latest/import/feature?projectKey=TC to respond... (10 seconds)
build	26-Aug-2024 15:38:19	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/raven/latest/import/feature?projectKey=TC to respond... (10 seconds)
build	26-Aug-2024 15:38:26	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/api/latest/issue/TC-xxxx to respond... (10 seconds)
build	26-Aug-2024 15:38:32	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/api/latest/issue/TC-xxxx to respond... (10 seconds)
build	26-Aug-2024 15:38:33	│ Cypress Xray Plugin │ INFO    │ Waiting for https://devstack.vwgroup.com/jira/rest/api/latest/issue/TC-xxxx to respond... (10 seconds)
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Parsing feature file: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
.
.
.
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
.
.
.
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ WARNING │ Encountered problems during plugin execution!
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ WARNING │ No test results were uploaded
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Failed to import Cucumber execution results
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
build	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ INFO    │ Importing feature file to Xray: /appl/bamboo-agent/xml-data/build-dir/TC-SBFRNT398-RET/frontend/cypress/e2e/features/generated_features/<file>.generated.feature
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Feature file import failed
.
.
.
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Failed to search for issues
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Failed to search for issues
error	26-Aug-2024 15:39:15	│ Cypress Xray Plugin │ ERROR   │ Failed to search for issues

**Comment by faltfe** [comment]
Hi @csvtuda,
thanks for the great effort to provide such a fast fix. With the latest version 7.3.0 it seems to work again.

The only downside is that the build is now slower because of the delay. Not sure if it would be faster we a solution recommended by Atlassian but for the moment it is working for us.

**Comment by csvtuda** [comment]
> The only downside is that the build is now slower because of the delay. Normally the build takes about 30 minutes.

That's unfortunately to be expected when you have hundreds of feature files etc. in your project. Admittedly, I still need to optimise away some of the API calls (e.g. combine multiple issue searches into a single search when retrieving current summaries and so on), but I haven't found the time yet to implement such optimisation passes.

You can probably speed things up a little bit by defining separate rate limits for Xray and Jira. The configuration I suggested above adds a global rate limit to _all_ requests, regardless of host.

```ts
await configureXrayPlugin(on, config, {
    http: {
        jira: {
            rateLimiting: {
                requestsPerSecond: // ...
            }
        },
        // If needed
        // xray: {
        //    rateLimiting: {
        //        requestsPerSecond: // ...
        //    }
        // }
    },
});
```

(this will only work for Xray/Jira cloud, since on server both APIs reside on the same host)

I'll close this as completed for now.
